extra_fn_clean_exts:
    - type: remove
      pattern: _snpEff

fn_ignore_files:
    - '*.g_snpEff.*'
    - '*.g.bcf.tools.stats.out'

fn_ignore_dirs:
    - 'work'

remove_sections:
    - 'mosdepth-coverage-per-contig-section'

table_columns_visible:
    FastQC: False
    Duplication: False
    "≥ 10X": True
    "Bcftools: Stats":
        "Ts/Tv": False
    "Samtools: stats":
        "Error rate": False
        "Non-primary": False

table_sample_merge:
  "MarkDuplicates": ".md"
  "Recalibrated": ".recal"
  "Custom stats": ".custom_stats"
  "DeepVariant": ".deepvariant"
  "HaplotypeCaller": ".haplotypecaller"
