#!/bin/sh
#SBATCH -A ngi2016001
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 10-00:00:00
#SBATCH -J methylSeq__PROJECT_
#SBATCH -e _ANALYSISDIR_/_PROJECT_/logs/methylSeq_%j.log
#SBATCH -o _ANALYSISDIR_/_PROJECT_/logs/methylSeq_%j.log

# Source NGI environment
source _ENVPATH_/conf/sourceme_upps.sh
source activate NGI

#set Nextflow env variables
export NXF_WORK=_ANALYSISDIR_/_PROJECT_/work

methylseq -resume --genome _GENOME_ \
    --input '_DATADIR_/merged_fastqs__PROJECT_/*_R{1,2}.fastq.gz' \
    --outdir _ANALYSISDIR_/_PROJECT_/results

# some files get very restrictive permissions, so change them
chgrp -R ngi2016001 _ANALYSISDIR_/_PROJECT_/results/pipeline_info
